// website/src/app/pages/track-order/track-order-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { LucideAngularModule } from 'lucide-angular';
import { HttpErrorResponse } from '@angular/common/http';
import { Order, OrderItem } from '../../core/models/order.model';
import { API_BASE_URL } from '../../core/services/api.config';
import { AuthStateService } from '../../core/services/auth-state.service';
import { OrderService } from '../../core/services/order.service';

interface TrackingStep {
  status: string;
  description: string;
  icon: string;
  completed: boolean;
  current: boolean;
  timestamp: Date;
}

@Component({
  selector: 'app-track-order-page',
  imports: [CommonModule, FormsModule, RouterLink, LucideAngularModule],
  templateUrl: './track-order-page.component.html',
  styleUrl: './track-order-page.component.css'
})
export class TrackOrderPageComponent {
  private readonly mediaBaseUrl = API_BASE_URL.replace(/\/api\/v1$/, '');
  private readonly authState = inject(AuthStateService);
  private readonly orderService = inject(OrderService);

  readonly isLoggedIn = this.authState.isAuthenticated;
  readonly trackedOrder = signal<Order | null>(null);
  readonly trackingSteps = computed(() => this.buildTrackingSteps(this.trackedOrder()));
  readonly privateDetailsVisible = computed(
    () => this.trackedOrder()?.privateDetailsVisible ?? false
  );
  readonly brokenImageIds = signal<Record<string, true>>({});
  readonly loading = signal(false);
  readonly searched = signal(false);
  readonly errorMessage = signal('');

  orderNumber = '';

  accountOrdersRoute(): string {
    return this.authState.accountRoute('orders');
  }

  contactRoute(): string {
    return '/contact';
  }

  trackOrder(): void {
    const normalized = this.normalizeOrderNumber(this.orderNumber);
    this.searched.set(true);
    this.errorMessage.set('');
    this.trackedOrder.set(null);
    this.brokenImageIds.set({});

    if (!normalized) {
      this.errorMessage.set('Enter your order number first.');
      return;
    }

    this.loading.set(true);
    this.orderService
      .trackOrder(normalized)
      .subscribe({
        next: (order) => {
          this.loading.set(false);
          this.trackedOrder.set(order);
        },
        error: (error: HttpErrorResponse) => {
          this.loading.set(false);
          this.trackedOrder.set(null);

          if (error.status === 404) {
            this.errorMessage.set('No matching order was found.');
            return;
          }

          if (error.status === 400) {
            this.errorMessage.set('Enter a valid order number.');
            return;
          }

          this.errorMessage.set('Tracking is temporarily unavailable. Please try again.');
        }
      });
  }

  statusPillClass(status: string): string {
    switch (status.toUpperCase()) {
      case 'PENDING':
        return 'bg-amber-50 text-amber-700 border-amber-200';
      case 'PROCESSING':
        return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'SHIPPED':
        return 'bg-violet-50 text-violet-700 border-violet-200';
      case 'DELIVERED':
      case 'COMPLETED':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200';
      case 'CANCELLED':
        return 'bg-rose-50 text-rose-700 border-rose-200';
      default:
        return 'bg-slate-100 text-slate-600 border-slate-200';
    }
  }

  deliveryLabel(order: Order): string {
    switch (order.status.toUpperCase()) {
      case 'DELIVERED':
      case 'COMPLETED':
        return 'Delivered';
      case 'SHIPPED':
        return 'On the way';
      case 'PROCESSING':
        return 'Preparing order';
      case 'CANCELLED':
        return 'Order cancelled';
      default:
        return 'Order received';
    }
  }

  publicDeliverySummary(order: Order): string {
    switch (order.status.toUpperCase()) {
      case 'DELIVERED':
      case 'COMPLETED':
        return 'Package delivered to the destination area.';
      case 'SHIPPED':
        return 'Package is currently moving through delivery.';
      case 'PROCESSING':
        return 'Shipment is being prepared for dispatch.';
      case 'CANCELLED':
        return 'Delivery updates stopped because the order was cancelled.';
      default:
        return 'Order has been registered and is waiting for the next update.';
    }
  }

  publicCustomerSummary(): string {
    return this.isLoggedIn()
      ? 'Full customer details are visible only for the account that placed this order.'
      : 'Customer details stay protected on public tracking pages.';
  }

  publicCustomerHint(): string {
    return this.isLoggedIn()
      ? 'Sign in with the purchasing account to unlock address, payment, and item details.'
      : 'Sign in with the purchasing account to view full order details.';
  }

  statusHeadline(order: Order): string {
    switch (order.status.toUpperCase()) {
      case 'DELIVERED':
      case 'COMPLETED':
        return 'Delivered successfully';
      case 'SHIPPED':
        return 'Out for delivery';
      case 'PROCESSING':
        return 'Processing your order';
      case 'CANCELLED':
        return 'This order was cancelled';
      default:
        return 'Order confirmed';
    }
  }

  statusIcon(order: Order): string {
    switch (order.status.toUpperCase()) {
      case 'DELIVERED':
      case 'COMPLETED':
        return 'house';
      case 'SHIPPED':
        return 'truck';
      case 'PROCESSING':
        return 'package';
      case 'CANCELLED':
        return 'circle-x';
      default:
        return 'circle-check';
    }
  }

  orderAddressLines(order: Order): string[] {
    return [
      order.shippingAddressLine1,
      order.shippingAddressLine2,
      `${order.shippingCity}${order.shippingState ? ', ' + order.shippingState : ''}`,
      order.shippingCountry
    ].filter(Boolean) as string[];
  }

  productTitle(item: OrderItem, index: number): string {
    return item.productName?.trim() || item.sku?.trim() || `Product ${index + 1}`;
  }

  productImageUrl(item: OrderItem): string | null {
    if (this.brokenImageIds()[item.id]) {
      return null;
    }

    const imageUrl = item.imageUrl?.trim();
    if (!imageUrl) {
      return null;
    }

    if (/^https?:\/\//i.test(imageUrl)) {
      return imageUrl;
    }

    return `${this.mediaBaseUrl}${imageUrl.startsWith('/') ? '' : '/'}${imageUrl}`;
  }

  markImageError(itemId: string): void {
    this.brokenImageIds.update((state) => ({ ...state, [itemId]: true }));
  }

  private normalizeOrderNumber(value: string): string {
    return value.trim().replace(/^#/, '').toUpperCase();
  }

  private buildTrackingSteps(order: Order | null): TrackingStep[] {
    if (!order) {
      return [];
    }

    const placedAt = new Date(order.placedAt);
    const stage = this.statusStage(order.status);

    return [
      {
        status: 'Order Placed',
        description: 'Your order was confirmed and saved to your account.',
        icon: 'circle-check',
        completed: true,
        current: stage === 0,
        timestamp: placedAt
      },
      {
        status: 'Processing',
        description: 'We are preparing your products for shipment.',
        icon: 'package',
        completed: stage >= 1,
        current: stage === 1,
        timestamp: this.addHours(placedAt, 6)
      },
      {
        status: 'Shipped',
        description: 'Your package has left the warehouse.',
        icon: 'truck',
        completed: stage >= 2,
        current: stage === 2,
        timestamp: this.addHours(placedAt, 24)
      },
      {
        status: 'Delivered',
        description:
          order.status.toUpperCase() === 'CANCELLED'
            ? 'Delivery stopped because the order was cancelled.'
            : 'Package delivered to the selected address.',
        icon: order.status.toUpperCase() === 'CANCELLED' ? 'circle-x' : 'house',
        completed: ['DELIVERED', 'COMPLETED'].includes(order.status.toUpperCase()),
        current: stage === 3,
        timestamp: this.addHours(placedAt, 48)
      }
    ];
  }

  private statusStage(status: string): number {
    switch (status.toUpperCase()) {
      case 'PENDING':
        return 0;
      case 'PROCESSING':
        return 1;
      case 'SHIPPED':
        return 2;
      case 'DELIVERED':
      case 'COMPLETED':
      case 'CANCELLED':
        return 3;
      default:
        return 0;
    }
  }

  private addHours(date: Date, hours: number): Date {
    return new Date(date.getTime() + hours * 60 * 60 * 1000);
  }
}

<div class="bg-slate-50 py-8 md:py-12">
  <div class="container mx-auto px-4">
    <div class="mb-8">
      <p class="text-sm font-bold uppercase tracking-[0.2em] text-primary">Order Tracking</p>
      <h1 class="mt-2 text-3xl font-black text-slate-900 md:text-4xl">Track Your Order</h1>
      <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600 md:text-base">
        Enter the order number from your confirmation email to review shipping progress and order details.
      </p>
    </div>

    <section class="mb-8 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
      <div class="flex flex-col gap-4 md:flex-row md:items-end">
        <div class="flex-1">
          <label for="orderNumber" class="mb-2 block text-sm font-semibold text-slate-700">Order Number</label>
          <input
            id="orderNumber"
            type="text"
            [(ngModel)]="orderNumber"
            placeholder="Example: ORD-2026-001"
            class="h-12 rounded-xl border-2 border-slate-200 bg-white"
          />
        </div>
        <button
          type="button"
          class="inline-flex h-12 items-center justify-center rounded-xl bg-primary px-8 text-sm font-bold text-white"
          [disabled]="loading()"
          (click)="trackOrder()"
        >
          <lucide-icon name="search" [size]="18" class="mr-2"></lucide-icon>
          {{ loading() ? 'Checking...' : 'Track Order' }}
        </button>
      </div>
      <p class="mt-3 text-sm text-slate-500">You can find the order number in your order confirmation email or your account order history.</p>
    </section>

    @if (errorMessage()) {
      <p class="mb-8 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ errorMessage() }}</p>
    }

    @if (trackedOrder(); as order) {
      <section class="mb-8 rounded-[2rem] border-2 border-primary bg-white p-6 shadow-sm">
        <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div class="flex items-start gap-4">
            <div class="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-white">
              <lucide-icon [name]="statusIcon(order)" [size]="30"></lucide-icon>
            </div>
            <div>
              <h2 class="text-2xl font-black text-slate-900">{{ statusHeadline(order) }}</h2>
              <p class="mt-1 text-sm text-slate-500">Order #{{ order.orderNumber }}</p>
              <p class="mt-2 text-sm text-slate-500">Placed on {{ order.placedAt | date: 'medium' }}</p>
            </div>
          </div>
          <div class="rounded-xl border px-4 py-2 text-sm font-semibold" [class]="statusPillClass(order.status)">
            {{ deliveryLabel(order) }}
          </div>
        </div>
      </section>

      <div class="track-order-layout grid gap-8">
        <div class="space-y-8">
          <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
            <h3 class="text-xl font-black text-slate-900">Tracking Details</h3>
            <div class="mt-6 space-y-6">
              @for (step of trackingSteps(); track step.status; let isLast = $last) {
                <div class="tracking-step relative flex gap-4">
                  @if (!isLast) {
                    <div class="tracking-step__line" [class.tracking-step__line--completed]="step.completed"></div>
                  }
                  <div
                    class="tracking-step__icon"
                    [class.tracking-step__icon--completed]="step.completed"
                    [class.tracking-step__icon--current]="step.current"
                  >
                    <lucide-icon [name]="step.icon" [size]="18"></lucide-icon>
                  </div>
                  <div class="flex-1 pb-8">
                    <div class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
                      <div>
                        <h4 class="text-lg font-bold text-slate-900">
                          {{ step.status }}
                          @if (step.current) {
                            <span class="ml-2 rounded-full bg-primary px-2 py-0.5 text-xs font-semibold text-white">Current</span>
                          }
                        </h4>
                        <p class="mt-1 text-sm text-slate-600">{{ step.description }}</p>
                      </div>
                      <p class="text-sm text-slate-500">{{ step.timestamp | date: 'medium' }}</p>
                    </div>
                  </div>
                </div>
              }
            </div>
          </section>

          @if (privateDetailsVisible()) {
            <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
              <div class="mb-6 flex items-center justify-between">
                <h3 class="text-xl font-black text-slate-900">Order Items ({{ order.items.length }})</h3>
                <a [routerLink]="accountOrdersRoute()" class="text-sm font-semibold text-primary hover:underline">View all orders</a>
              </div>

              <div class="space-y-4">
                @for (item of order.items; track item.id; let itemIndex = $index) {
                  <div class="flex items-center gap-4 border-b border-slate-200 pb-4 last:border-b-0">
                    <div class="order-item-media flex h-[4.5rem] w-[4.5rem] items-center justify-center overflow-hidden rounded-2xl bg-slate-100 text-slate-400">
                      @if (productImageUrl(item); as imageUrl) {
                        <img
                          [src]="imageUrl"
                          [alt]="productTitle(item, itemIndex)"
                          class="order-item-media__image"
                          loading="lazy"
                          (error)="markImageError(item.id)"
                        />
                      } @else {
                        <lucide-icon name="package" [size]="26"></lucide-icon>
                      }
                    </div>
                    <div class="flex-1">
                      <h4 class="font-semibold text-slate-900">{{ productTitle(item, itemIndex) }}</h4>
                      <p class="mt-1 text-sm text-slate-500">
                        Qty: {{ item.quantity }}
                        @if (item.sku) {
                          <span class="mx-1 text-slate-300">|</span>
                          SKU: {{ item.sku }}
                        }
                      </p>
                    </div>
                    <div class="text-right">
                      <p class="font-bold text-slate-900">{{ item.lineTotal | number: '1.2-2' }} DH</p>
                    </div>
                  </div>
                }
              </div>

              <div class="mt-6 space-y-2 border-t border-slate-200 pt-4">
                <div class="flex justify-between text-sm text-slate-600">
                  <span>Subtotal</span>
                  <span>{{ order.subtotal | number: '1.2-2' }} DH</span>
                </div>
                <div class="flex justify-between text-sm text-slate-600">
                  <span>Shipping</span>
                  <span>{{ order.shippingAmount | number: '1.2-2' }} DH</span>
                </div>
                <div class="flex justify-between text-sm text-slate-600">
                  <span>Tax</span>
                  <span>{{ order.taxAmount | number: '1.2-2' }} DH</span>
                </div>
                <div class="flex justify-between border-t border-slate-200 pt-3 text-lg font-black text-slate-900">
                  <span>Total</span>
                  <span class="text-primary">{{ order.totalAmount | number: '1.2-2' }} DH</span>
                </div>
              </div>
            </section>
          }
        </div>

        <div class="space-y-6">
          @if (privateDetailsVisible()) {
            <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
              <h3 class="flex items-center gap-2 text-lg font-black text-slate-900">
                <lucide-icon name="map-pin" [size]="18" class="text-primary"></lucide-icon>
                Delivery Address
              </h3>
              <div class="mt-4 space-y-2 text-sm text-slate-600">
                <p class="font-semibold text-slate-900">{{ order.shippingRecipientName }}</p>
                @for (line of orderAddressLines(order); track line) {
                  <p>{{ line }}</p>
                }
                @if (order.shippingPhone) {
                  <div class="mt-4 flex items-center gap-2 border-t border-slate-200 pt-4">
                    <lucide-icon name="phone" [size]="16"></lucide-icon>
                    <span>{{ order.shippingPhone }}</span>
                  </div>
                }
                @if (order.shippingEmail) {
                  <div class="flex items-center gap-2">
                    <lucide-icon name="mail" [size]="16"></lucide-icon>
                    <span>{{ order.shippingEmail }}</span>
                  </div>
                }
              </div>
            </section>

            <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
              <h3 class="flex items-center gap-2 text-lg font-black text-slate-900">
                <lucide-icon name="receipt" [size]="18" class="text-primary"></lucide-icon>
                Order Information
              </h3>
              <div class="mt-4 space-y-3 text-sm text-slate-600">
                <div>
                  <p class="text-slate-500">Payment Method</p>
                  <p class="font-semibold text-slate-900">{{ order.paymentMethod }}</p>
                </div>
                <div>
                  <p class="text-slate-500">Payment Status</p>
                  <p class="font-semibold text-slate-900">{{ order.paymentStatus }}</p>
                </div>
                <div>
                  <p class="text-slate-500">Customer Type</p>
                  <p class="font-semibold text-slate-900">{{ order.customerType }}</p>
                </div>
                @if (order.couponCode) {
                  <div>
                    <p class="text-slate-500">Coupon</p>
                    <p class="font-semibold text-slate-900">{{ order.couponCode }}</p>
                  </div>
                }
              </div>
            </section>
          }
          @else {
            <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
              <h3 class="flex items-center gap-2 text-lg font-black text-slate-900">
                <lucide-icon name="truck" [size]="18" class="text-primary"></lucide-icon>
                Delivery Info
              </h3>
              <div class="mt-4 space-y-3 text-sm text-slate-600">
                <div>
                  <p class="text-slate-500">Current Status</p>
                  <p class="font-semibold text-slate-900">{{ deliveryLabel(order) }}</p>
                </div>
                <div>
                  <p class="text-slate-500">Placed On</p>
                  <p class="font-semibold text-slate-900">{{ order.placedAt | date: 'medium' }}</p>
                </div>
                <div>
                  <p class="text-slate-500">Update</p>
                  <p class="leading-6">{{ publicDeliverySummary(order) }}</p>
                </div>
              </div>
            </section>

            <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">
              <h3 class="flex items-center gap-2 text-lg font-black text-slate-900">
                <lucide-icon name="user" [size]="18" class="text-primary"></lucide-icon>
                Customer Info
              </h3>
              <div class="mt-4 space-y-3 text-sm text-slate-600">
                <div>
                  <p class="text-slate-500">Privacy</p>
                  <p class="font-semibold text-slate-900">Protected</p>
                </div>
                <div>
                  <p class="leading-6">{{ publicCustomerSummary() }}</p>
                </div>
                <div class="rounded-2xl bg-slate-50 px-4 py-3 text-slate-500">
                  {{ publicCustomerHint() }}
                </div>
              </div>
            </section>
          }

          <section class="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <h3 class="text-base font-black text-slate-900">Need Help?</h3>
            <p class="mt-3 text-sm leading-6 text-slate-600">
              If something looks wrong, contact support for manual follow-up.
            </p>
            <div class="mt-5 space-y-3">
              @if (privateDetailsVisible() && isLoggedIn()) {
                <a [routerLink]="accountOrdersRoute()" class="inline-flex w-full items-center justify-center rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700">
                  My Orders
                </a>
              }
              <a [routerLink]="contactRoute()" class="inline-flex w-full items-center justify-center rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white">
                Contact Support
              </a>
            </div>
          </section>
        </div>
      </div>
    } @else if (searched() && !errorMessage() && !loading()) {
      <section class="rounded-[2rem] border border-slate-200 bg-white p-10 text-center shadow-sm">
        <lucide-icon name="search" [size]="56" class="mx-auto text-slate-300"></lucide-icon>
        <h2 class="mt-4 text-2xl font-black text-slate-900">No matching order yet</h2>
        <p class="mt-3 text-sm text-slate-600">Check the order number format and try again.</p>
      </section>
    } @else if (!searched()) {
      <section class="rounded-[2rem] border-0 bg-gradient-to-br from-blue-50 to-indigo-50 p-10 text-center">
        <lucide-icon name="truck" [size]="64" class="mx-auto text-primary"></lucide-icon>
        <h2 class="mt-5 text-3xl font-black text-slate-900">Track your package from one page</h2>
        <p class="mx-auto mt-3 max-w-2xl text-sm leading-6 text-slate-600 md:text-base">
          Search by order number to review progress, shipping details, and the products included in the order.
        </p>
        <div class="mx-auto mt-8 grid max-w-3xl gap-4 md:grid-cols-3">
          <div class="rounded-[1.5rem] bg-white p-5 shadow-sm">
            <lucide-icon name="clock" [size]="30" class="mx-auto text-blue-600"></lucide-icon>
            <p class="mt-3 text-sm font-semibold text-slate-900">Real-time status</p>
          </div>
          <div class="rounded-[1.5rem] bg-white p-5 shadow-sm">
            <lucide-icon name="map-pin" [size]="30" class="mx-auto text-primary"></lucide-icon>
            <p class="mt-3 text-sm font-semibold text-slate-900">Delivery details</p>
          </div>
          <div class="rounded-[1.5rem] bg-white p-5 shadow-sm">
            <lucide-icon name="package" [size]="30" class="mx-auto text-emerald-600"></lucide-icon>
            <p class="mt-3 text-sm font-semibold text-slate-900">Order summary</p>
          </div>
        </div>
      </section>
    }
  </div>
</div>

// E-commerce Website Design/src/app/pages/TrackOrderPage.tsx
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { 
  Package, 
  MapPin, 
  Clock, 
  CheckCircle2,
  Truck,
  Home,
  Phone,
  Mail,
  Search
} from 'lucide-react';

export function TrackOrderPage() {
  const [orderNumber, setOrderNumber] = useState('');
  const [showTracking, setShowTracking] = useState(false);

  const handleTrack = () => {
    setShowTracking(true);
  };

  const trackingSteps = [
    {
      status: 'Order Placed',
      date: 'March 5, 2026',
      time: '10:30 AM',
      description: 'Your order has been confirmed',
      icon: CheckCircle2,
      completed: true
    },
    {
      status: 'Processing',
      date: 'March 5, 2026',
      time: '2:15 PM',
      description: 'Your order is being prepared',
      icon: Package,
      completed: true
    },
    {
      status: 'Shipped',
      date: 'March 6, 2026',
      time: '9:00 AM',
      description: 'Package has been picked up by courier',
      icon: Truck,
      completed: true
    },
    {
      status: 'Out for Delivery',
      date: 'March 7, 2026',
      time: '8:30 AM',
      description: 'Package is on its way to you',
      icon: MapPin,
      completed: true,
      current: true
    },
    {
      status: 'Delivered',
      date: 'Expected today',
      time: 'By 6:00 PM',
      description: 'Package will be delivered',
      icon: Home,
      completed: false
    }
  ];

  const orderItems = [
    {
      id: 1,
      name: 'Premium Olive Oil',
      image: 'https://images.unsplash.com/photo-1765850257647-811b8d3c20ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbGl2ZSUyMG9pbCUyMHByZW1pdW18ZW58MXx8fHwxNzcyOTI4MDg0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      quantity: 2,
      price: 12.99
    },
    {
      id: 2,
      name: 'Organic Orange Juice',
      image: 'https://images.unsplash.com/photo-1640213505284-21352ee0d76b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmFuZ2UlMjBqdWljZSUyMGJvdHRsZXxlbnwxfHx8fDE3NzI4NDQzMjJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      quantity: 1,
      price: 5.99
    },
    {
      id: 3,
      name: 'Natural Honey',
      image: 'https://images.unsplash.com/photo-1645549826194-1956802d83c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob25leSUyMGphciUyMG5hdHVyYWx8ZW58MXx8fHwxNzcyOTA5MjY0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      quantity: 1,
      price: 14.99
    }
  ];

  return (
    <div className="bg-gray-50 min-h-screen py-8">
      <div className="container mx-auto px-4">
        {/* Page Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Track Your Order</h1>
          <p className="text-gray-600">Enter your order number to track your delivery</p>
        </div>

        {/* Track Order Form */}
        <Card className="mb-8">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1">
                <Label htmlFor="orderNumber" className="mb-2 block">Order Number</Label>
                <Input 
                  id="orderNumber"
                  placeholder="e.g. ORD-2026-001"
                  value={orderNumber}
                  onChange={(e) => setOrderNumber(e.target.value)}
                  className="h-12"
                />
              </div>
              <div className="flex items-end">
                <Button 
                  onClick={handleTrack}
                  className="bg-[#003d82] hover:bg-[#002d62] h-12 px-8"
                >
                  <Search className="h-5 w-5 mr-2" />
                  Track Order
                </Button>
              </div>
            </div>
            <p className="text-sm text-gray-500 mt-3">
              You can find your order number in the confirmation email we sent you.
            </p>
          </CardContent>
        </Card>

        {showTracking && (
          <>
            {/* Order Status Banner */}
            <Card className="mb-8 border-[#003d82] border-2">
              <CardContent className="p-6">
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                  <div className="flex items-start gap-4">
                    <div className="w-16 h-16 bg-[#003d82] rounded-full flex items-center justify-center flex-shrink-0">
                      <Truck className="h-8 w-8 text-white" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-bold text-gray-900 mb-1">Out for Delivery</h2>
                      <p className="text-gray-600 mb-2">Order #ORD-2026-001</p>
                      <p className="text-sm text-gray-500">Expected delivery: Today by 6:00 PM</p>
                    </div>
                  </div>
                  <div className="bg-green-50 text-green-700 px-4 py-2 rounded-lg border border-green-200">
                    <p className="text-sm font-medium">Arriving Today</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="grid lg:grid-cols-3 gap-8">
              {/* Tracking Timeline */}
              <div className="lg:col-span-2 space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle>Tracking Details</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-6">
                      {trackingSteps.map((step, index) => (
                        <div key={index} className="relative flex gap-4">
                          {/* Timeline Line */}
                          {index !== trackingSteps.length - 1 && (
                            <div 
                              className={`absolute left-5 top-12 w-0.5 h-16 ${
                                step.completed ? 'bg-[#003d82]' : 'bg-gray-200'
                              }`}
                            />
                          )}
                          
                          {/* Icon */}
                          <div 
                            className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 z-10 ${
                              step.completed 
                                ? step.current 
                                  ? 'bg-[#003d82] ring-4 ring-blue-100' 
                                  : 'bg-[#003d82]'
                                : 'bg-gray-200'
                            }`}
                          >
                            <step.icon className={`h-5 w-5 ${step.completed ? 'text-white' : 'text-gray-400'}`} />
                          </div>

                          {/* Content */}
                          <div className="flex-1 pb-8">
                            <div className="flex flex-col md:flex-row md:items-center justify-between mb-2">
                              <h3 className={`font-semibold text-lg ${step.current ? 'text-[#003d82]' : 'text-gray-900'}`}>
                                {step.status}
                                {step.current && (
                                  <span className="ml-2 text-sm bg-[#003d82] text-white px-2 py-0.5 rounded-full">
                                    Current
                                  </span>
                                )}
                              </h3>
                              <div className="flex items-center gap-2 text-sm text-gray-500">
                                <Clock className="h-4 w-4" />
                                <span>{step.date} • {step.time}</span>
                              </div>
                            </div>
                            <p className="text-gray-600">{step.description}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>

                {/* Order Items */}
                <Card>
                  <CardHeader>
                    <CardTitle>Order Items ({orderItems.length})</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {orderItems.map((item) => (
                        <div key={item.id} className="flex gap-4 pb-4 border-b last:border-0">
                          <div className="w-20 h-20 bg-gray-100 rounded-lg overflow-hidden flex-shrink-0">
                            <img 
                              src={item.image} 
                              alt={item.name}
                              className="w-full h-full object-cover"
                            />
                          </div>
                          <div className="flex-1">
                            <h4 className="font-medium text-gray-900 mb-1">{item.name}</h4>
                            <p className="text-sm text-gray-600">Quantity: {item.quantity}</p>
                          </div>
                          <div className="text-right">
                            <p className="font-semibold text-gray-900">${(item.price * item.quantity).toFixed(2)}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    
                    <div className="mt-6 pt-4 border-t space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Subtotal</span>
                        <span className="font-medium">$43.97</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Shipping</span>
                        <span className="font-medium text-green-600">Free</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Tax</span>
                        <span className="font-medium">$3.52</span>
                      </div>
                      <div className="flex justify-between text-lg font-bold pt-2 border-t">
                        <span>Total</span>
                        <span className="text-[#003d82]">$47.49</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Sidebar Info */}
              <div className="space-y-6">
                {/* Delivery Address */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <MapPin className="h-5 w-5 text-[#003d82]" />
                      Delivery Address
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2 text-sm">
                      <p className="font-medium text-gray-900">John Doe</p>
                      <p className="text-gray-600">123 Main Street, Apt 4B</p>
                      <p className="text-gray-600">New York, NY 10001</p>
                      <div className="pt-3 border-t mt-3">
                        <div className="flex items-center gap-2 text-gray-600">
                          <Phone className="h-4 w-4" />
                          <span>+1 (555) 123-4567</span>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Delivery Info */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Truck className="h-5 w-5 text-[#003d82]" />
                      Delivery Information
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3 text-sm">
                      <div>
                        <p className="text-gray-600 mb-1">Courier</p>
                        <p className="font-medium">Express Delivery Co.</p>
                      </div>
                      <div>
                        <p className="text-gray-600 mb-1">Tracking Number</p>
                        <p className="font-medium">TRK789456123</p>
                      </div>
                      <div>
                        <p className="text-gray-600 mb-1">Delivery Method</p>
                        <p className="font-medium">Standard Shipping</p>
                      </div>
                      <div>
                        <p className="text-gray-600 mb-1">Estimated Delivery</p>
                        <p className="font-medium text-[#003d82]">Today by 6:00 PM</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Contact Support */}
                <Card className="bg-gray-50">
                  <CardHeader>
                    <CardTitle className="text-base">Need Help?</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <p className="text-sm text-gray-600">
                      Have questions about your order? Our customer support team is here to help.
                    </p>
                    <div className="space-y-2">
                      <Button variant="outline" className="w-full justify-start">
                        <Phone className="h-4 w-4 mr-2" />
                        Call Support
                      </Button>
                      <Button variant="outline" className="w-full justify-start">
                        <Mail className="h-4 w-4 mr-2" />
                        Email Support
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </>
        )}

        {!showTracking && (
          <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 border-0">
            <CardContent className="p-12 text-center">
              <Package className="h-20 w-20 mx-auto text-[#003d82] mb-6" />
              <h3 className="text-2xl font-bold mb-3">Track Your Package</h3>
              <p className="text-gray-600 max-w-md mx-auto mb-6">
                Enter your order number above to see real-time tracking information and delivery updates.
              </p>
              <div className="grid md:grid-cols-3 gap-4 max-w-2xl mx-auto mt-8">
                <div className="bg-white p-4 rounded-lg shadow-sm">
                  <CheckCircle2 className="h-8 w-8 text-green-600 mx-auto mb-2" />
                  <p className="text-sm font-medium">Real-time Updates</p>
                </div>
                <div className="bg-white p-4 rounded-lg shadow-sm">
                  <Truck className="h-8 w-8 text-blue-600 mx-auto mb-2" />
                  <p className="text-sm font-medium">Delivery Status</p>
                </div>
                <div className="bg-white p-4 rounded-lg shadow-sm">
                  <MapPin className="h-8 w-8 text-purple-600 mx-auto mb-2" />
                  <p className="text-sm font-medium">Location Tracking</p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
